### ISSUE TITLE
Filtry

### ISSUE THREAD

**Issue by Wrent** [vernepa1/taxi_coordination#3]
- přepínání filtrů
 - aktualizace dat na mapě - bude třeba implementovat některé položky v DB (např. VIP) a zároveň pravděpodobně udělat více init dat (případně napsat nějaký generátor, aby bylo vidět, že to fakt funguje)

**Comment by Wrent** [comment]
Pro prepinani obarveni uzlu lze vyuzit implementovanou funkci buttonSwitcher

**Comment by JanBliznicenko** [comment]
kde je implementovana? nejak nic s takovym nazvem nemuzu najit

**Comment by Wrent** [comment]
v custom.js, sorry, zapomnel jsem pushnout :/
