### ISSUE TITLE
Rešerše konkurence

### ISSUE THREAD

**Issue by Wrent** [vernepa1/taxi_coordination#6]
Zpracovat rešerši 7 podobných nebo konkurenčních řešení, viz edux

**Comment by JanBliznicenko** [comment]
tohle bude orisek, kdyz maloco z toho je nejak na vyzkouseni - clovek muze byt rad za par reklamnich sloganu a 1 obrazek a kdyz uz je tam nejaky trial nebo demo, tak ne uplne snadno dosazitelny...
kazdopadne co jsem tak nejak nasel:
http://taxify.eu/cs/dispecer-uvodni-stranka/
http://www.taxicaller.com/dispatch_software.php
http://mobisoftinfotech.com/products/taxi-dispatch-software
http://www.mtaxiapp.com/en/company.html
https://www.shiftdispatch.com/features
http://taxi-dispatch-system.co.uk/
http://www.taximobility.com/features.html
http://mobisoftinfotech.com/products/taxi-apps-development-solutions
https://www.infinitecab.com/demo/admin/Home
http://www.taxicommander.com/taxi-dispatch-professional/
http://www.limontaxi.com/fleet/

**Comment by Wrent** [comment]
neco je i v dokumentu na Drive uz :) - v podstate jsme rikali ze cokoli co
pouziva mapu se hodi

Adam Kučera
adam.kucera@wrent.cz
+420608921904

2016-12-06 17:03 GMT+01:00 Jan Blizničenko <notifications@github.com>:

**Comment by Wrent** [comment]
https://docs.google.com/document/d/1TClzKRZQmeA4YPBmuJmcj9EnKnoiEc3ROpc7dLnM9EY/edit
