### ISSUE TITLE
input na rychle filtrovani taxi (feedback z odevzdani prvni casti)

### ISSUE THREAD

**Issue by Wrent** [vernepa1/taxi_coordination#8]

**Comment by JanBliznicenko** [comment]
TIm se mysli textove vyhledavani napriklad dle jmena ridice, modelu auta apod.?

**Comment by Wrent** [comment]
dejme tomu jmeno ridice, zakaznika a mozna jeste treba telefon zakaznika? Hunka to hlavne rikal, ze je to potreba, kdyz ti treba zakaznik zavola, ze meni objednavku (tak ho ted nemame jak rychle najit)
